--insert into TODO
--values(10001, 'learn spring boot', false, sysdate(), 'cyy' );
--insert into TODO
--values(10002, 'learn javascript', false, sysdate(), 'cyy' );
--insert into TODO
--values(10003, 'learn to dance', false, sysdate(), 'cyy' );